language: python

python:
    - "3.5"

sudo: false

env:
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
  - TOX_ENV=lint
  - TOX_ENV=coverage
  - TOX_ENV=docs

install:
  - pip install tox coveralls
  # see the following issue: https://github.com/travis-ci/travis-ci/issues/5485#issuecomment-173837358
  - pip install "virtualenv<14"

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e $TOX_ENV

notifications:
    email: false

addons:
  apt_packages:
    - pandoc
deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      l+ImrClIvD/LYsqr5KIKhBBFYBtDAfDhWYnW/tdZGpkPTDy0hWdf1+KaLc7tvb1gmG8eKEM/ErN8vfZM+6Etjo9znMgp60WSk4wyjWwkHX2Yc
      4EYHeyJ1YOVo/nhNdlFMl3R/1ynOB1qWN4+5VvHdpatuPMquPqShqZzwxUi9HJfCAUVPf1NKfnCzuHT1L3+mWtw40sjDPVH74e5suIHw36GJG
      jx1ioUMk+1IyRk5afiJ3Ye6FqHbOS0Oe7LWx2wCLXrzJyqrGCOcjh8wegW3fVBf5yCe14+pT76kHC81Q3FgbRoqNRUaxgUdKzy5m5RYqXNVza
      LG5lFJJzei/OC414G+Pls=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/tg-option-container
