language: python

python:
    - "3.5"

sudo: false

env:
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
  - TOX_ENV=lint
  - TOX_ENV=coverage
  - TOX_ENV=docs

install:
  - pip install tox coveralls
  # see the following issue: https://github.com/travis-ci/travis-ci/issues/5485#issuecomment-173837358
  - pip install "virtualenv<14"

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e $TOX_ENV

notifications:
    email: false

addons:
  apt_packages:
    - pandoc
deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      cTZ36o0PKte+YaJmmtSvoIGbyfmOlnDeJMUXJ/hBXOQ0QDFCmEXodTKb4pBc4CPk2H4vg09mc4XNWjPAfdOXuJrIoTZHOMjexvWxZY2hSbjJP
      hNc6VURgjwih5R9SAvEg3ySRac2pGeHwTgKavHpzJbUtbsVU0RsU9/bEhaDXJrtE2uV1Pq2zSbZWDMKgZMYCSDQmwM1FZQ/SGlTmTRgywNv1w
      Q3lFQ62WXaXe/hepwxIyCLV8B6OVbWc1n1MclcUfX5hGwg3qxbknGmI2x4ft4oyxSpBn4alTWFlhxemhCTccjCKPyXTn+7XNT5ApyWLSR38zq
      jm+wpUhP0dAHFeY9rUrSahX51rcDZ8B4f3an3Pt5MI4TOnN6bsgBD9zDeZ8gBSTMNspX40aati6avdx4xc7rcl8/oxTbFLo5PGNZeSe2CJgCO
      zwXtvqKCa45pi6gg41pscTBUu+qce458lzH4DHZ5HQhCpqW4WU65BvBNkEDGj1gC3hMANljx92JamnGbBc/gwAhmEtjYzpLb/+jOagxiSKqg0
      N/pXl1n3OhfOnIoccmsScgp5jgYxE71RM6otB92c+BNUxJ/OTy5zo5WehRji9Kmlx8Dm69KwsJmzFyEvNFTW/NuRZjodU4N+nezvoXZVmSuRV
      /prjMQaFMwKJhtE/zPV51ZDnxHRJ0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/tg-option-container
